import { defekt } from 'defekt';

const errors = defekt({
  AggregateDefinitionMalformed: {},
  AggregateNotFound: {},
  ApplicationNotFound: {},
  CommandHandlerMalformed: {},
  CommandMalformed: {},
  CommandNotFound: {},
  CommandRejected: {},
  CompilationFailed: {},
  ContextNotFound: {},
  CorsOriginInvalid: {},
  DatabaseTypeInvalid: {},
  DirectoryNotFound: {},
  DispatchFailed: {},
  DomainEventAlreadyExists: {},
  DomainEventHandlerMalformed: {},
  DomainEventNotAuthorized: {},
  DomainEventNotFound: {},
  DomainEventMalformed: {},
  DomainEventRejected: {},
  DomainEventUnknown: {},
  FileAlreadyExists: {},
  FileNotFound: {},
  IdentifierMismatch: {},
  InvalidOperation: {},
  ItemAlreadyExists: {},
  ItemIdentifierMalformed: {},
  ItemIdentifierNotFound: {},
  ItemNotFound: {},
  ItemNotLocked: {},
  LockExpired: {},
  NotAuthenticatedError: {},
  ProjectionHandlerMalformed: {},
  PublisherTypeInvalid: {},
  QueryHandlerMalformed: {},
  RequestFailed: {},
  RequestMalformed: {},
  SubscriberTypeInvalid: {},
  TokenMismatch: {},
  TypeInvalid: {},
  ViewDefinitionMalformed: {}
});

export { errors };
