# Right now, the Node.js mysql module does not support MySQL 8.x's new
# authentication mechanism.
#
# For details, see: https://github.com/mysqljs/mysql/issues/1959
# Updated PR for that: https://github.com/mysqljs/mysql/pull/2233

FROM mysql:8.0.22
LABEL maintainer="the native web <hello@thenativeweb.io>"
