# Right now, the Node.js mysql module does not support MySQL 8's new
# authentication mechanism. For details, see the following pull request:
# https://github.com/mysqljs/mysql/pull/1962

FROM mysql:5.7.21
LABEL maintainer="the native web <hello@thenativeweb.io>"
