'use strict';

const defekt = require('defekt');

const errors = defekt([
  'AddressMismatch',
  'ApplicationAlreadyRunning',
  'ApplicationBuilding',
  'ApplicationNotRunning',
  'ApplicationPartiallyRunning',
  'ApplicationRunning',
  'ApplicationTerminating',
  'ApplicationVerifyingConnections',
  'CertificateExpired',
  'CertificateMismatch',
  'CertificateNotYetValid',
  'CodeMalformed',
  'ConfigurationMalformed',
  'ConfigurationNotFound',
  'ConnectionRefused',
  'DirectoryEmpty',
  'DirectoryNotEmpty',
  'DirectoryNotFound',
  'DockerNotReachable',
  'EnvironmentNotAufwind',
  'EnvironmentNotFound',
  'EnvironmentVariableMissing',
  'EventStoreNotEmpty',
  'ExecutableFailed',
  'ExecutableNotFound',
  'ExportInvalid',
  'ExportNotFound',
  'FileAccessModeTooOpen',
  'FileNotAccessible',
  'FileNotFound',
  'FileStorageNotAccessible',
  'FileStorageBucketNotFound',
  'InfrastructureAlreadyRunning',
  'InfrastructureNotRunning',
  'InfrastructurePartiallyRunning',
  'JsonMalformed',
  'OutputMalformed',
  'PortsNotAvailable',
  'ProtocolInvalid',
  'RequestFailed',
  'RuntimeAlreadyInstalled',
  'RuntimeError',
  'RuntimeInUse',
  'RuntimeNotInstalled',
  'SecretFileNotFound',
  'SecretNotFound',
  'UnknownError',
  'UrlMalformed',
  'VersionMismatch',
  'VersionAlreadyInstalled',
  'VersionNotFound'
]);

module.exports = errors;
