FROM node:12.16.1-alpine
LABEL maintainer="the native web <hello@thenativeweb.io>"

# This Docker image is actually not used anywhere, it is just there to get
# updates by Dependabot to automatically get notified when new versions are
# available.
