name: QA

on: pull_request

jobs:
  qa:
    name: QA
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ '12.x' ]
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v1
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: |
        npm install
    - name: Run roboter
      run: |
        npx roboter
